name: Docker build and test Zephyr build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: zephyr-esp32-dev:test
          load: true  # load to local Docker so we can run it below

      - name: Clone target project (zephyr-atom-wifi-sample)
        run: git clone https://github.com/tamegai-m/zephyr-atom-wifi-sample target
        
      - name: Run build inside Docker
        run: |
            docker run --rm -v ${{ github.workspace }}:/work -w /work zephyr-esp32-dev:test \
              bash -c "\
                mkdir workspace && cd workspace && \
                west init && \
                west update && \
                west zephyr-export && \
                pip3 install -r zephyr/scripts/requirements.txt && \
                west build -b m5stack_atom_lite/esp32/procpu ../target"
        